// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WhiskyMan.Repositories;

namespace WhiskyMan.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20201222104031_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("WhiskyMan.Entities.Bottle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Amount_ml")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BottleDescriptionId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BottlePrice")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDrunk")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ShotPrice")
                        .HasColumnType("TEXT");

                    b.Property<int>("WastePercent")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BottleDescriptionId");

                    b.HasIndex("IsDrunk");

                    b.ToTable("Bottles");
                });

            modelBuilder.Entity("WhiskyMan.Entities.BottleDescription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DescriptionText")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Distillery")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PictureUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Voltage")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Active", "Id");

                    b.ToTable("BottleDescriptions");
                });

            modelBuilder.Entity("WhiskyMan.Entities.Ownership", b =>
                {
                    b.Property<int>("BottleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("BottleId", "OwnerId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Ownership");
                });

            modelBuilder.Entity("WhiskyMan.Entities.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Amount_ml")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BottleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BuyerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPayed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PaymentTime")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BottleId");

                    b.HasIndex("BuyerId");

                    b.HasIndex("CreationTime");

                    b.HasIndex("IsPayed", "CreationTime");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("WhiskyMan.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("BLOB");

                    b.Property<string>("PictureUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.HasIndex("Active", "Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WhiskyMan.Entities.Bottle", b =>
                {
                    b.HasOne("WhiskyMan.Entities.BottleDescription", "BottleDescription")
                        .WithMany("Bottles")
                        .HasForeignKey("BottleDescriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BottleDescription");
                });

            modelBuilder.Entity("WhiskyMan.Entities.Ownership", b =>
                {
                    b.HasOne("WhiskyMan.Entities.Bottle", "Bottle")
                        .WithMany("Ownerships")
                        .HasForeignKey("BottleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WhiskyMan.Entities.User", "Owner")
                        .WithMany("Ownerships")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bottle");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("WhiskyMan.Entities.Transaction", b =>
                {
                    b.HasOne("WhiskyMan.Entities.Bottle", "Bottle")
                        .WithMany("Transactions")
                        .HasForeignKey("BottleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WhiskyMan.Entities.User", "Buyer")
                        .WithMany("Transactions")
                        .HasForeignKey("BuyerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bottle");

                    b.Navigation("Buyer");
                });

            modelBuilder.Entity("WhiskyMan.Entities.Bottle", b =>
                {
                    b.Navigation("Ownerships");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("WhiskyMan.Entities.BottleDescription", b =>
                {
                    b.Navigation("Bottles");
                });

            modelBuilder.Entity("WhiskyMan.Entities.User", b =>
                {
                    b.Navigation("Ownerships");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
